creation_rules:
  - path_regex: 'repo-auth.yaml$'
    encrypted_regex: '^(data|stringData)$'
    age: >-
      age1vgjxqxjsgk0p46f0fyvnvxrd6sceuhqymyt4h5fsgaanrd2vt3yqpa0054,
      age1l94nxjefdnlew2lzdpr2dc52vm8qt024ql5nuyefar9g32ph7cxq8u6r7s
  - path_regex: 'reg.values.secrets.env$'
    encrypted_regex: '(PASSWORD|secret|key|token)'
    age: >-
      age1vgjxqxjsgk0p46f0fyvnvxrd6sceuhqymyt4h5fsgaanrd2vt3yqpa0054,
      age1l94nxjefdnlew2lzdpr2dc52vm8qt024ql5nuyefar9g32ph7cxq8u6r7s
  - path_regex: '.*\.?k8s\.yaml$|.*controlplane\.yaml$|.*talosconfig$'
    encrypted_regex: '^(.*PASSWORD.*|.*password.*|.*TOKEN.*|.*token.*|.*key.*|.*KEY.*|.dockerconfigjson|.*secret.*|.*SECRET.*|REGISTRY_HTPASSWD)$'
    age: >-
      age1vgjxqxjsgk0p46f0fyvnvxrd6sceuhqymyt4h5fsgaanrd2vt3yqpa0054,
      age1l94nxjefdnlew2lzdpr2dc52vm8qt024ql5nuyefar9g32ph7cxq8u6r7s
  - path_regex: '.*\.?secrets\.yaml$'
    encrypted_regex: '(password|secret|key|token|user)'
    age: >-
      age1vgjxqxjsgk0p46f0fyvnvxrd6sceuhqymyt4h5fsgaanrd2vt3yqpa0054,
      age1l94nxjefdnlew2lzdpr2dc52vm8qt024ql5nuyefar9g32ph7cxq8u6r7s
