apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - nodes.yaml
  - policies.yaml
  - networking.yaml
  - observability.yaml
  - platform.yaml
  - immich-database.yaml
  - immich.yaml
  - flux-ui.yaml
  - jellyfin.yaml
