apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: nodes
  interval: 2m
  path: ./platform/controllers
  prune: true
  retryInterval: 30s
  sourceRef:
    kind: OCIRepository
    name: homelab
  timeout: 10m
  wait: true
