apiVersion: v1
kind: Secret
metadata:
    creationTimestamp: null
    name: media-automation-credentials
    namespace: media
stringData:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:LFYp0vSKrG9GXZEygKP//McpR2aMCP5C7wPOxl1AX1E=,iv:OEZx2ptgqen/QrX0RJnFlrDIMZpNjGVyKexZDqjNrgg=,tag:zK1mUMJLtOJpr2lcXNiifA==,type:str]
    BAZARR_API_KEY: ENC[AES256_GCM,data:Jh3PUTxAJk/DYq8j7rbQjDeIY6QZn34WufTagCGBq1c=,iv:/9DRPV0tZPHlFqSXN4WrA01cdpnN1E/TGg08bwVjf7Q=,tag:XTP7uC4XZDS06TwrofAr5w==,type:str]
    JELLYFIN_PASSWORD: ENC[AES256_GCM,data:Ci+Bq/oxQUo=,iv:MPog1+yGyUzXO/6z/cqu7Gnc8sQrjYwIeYryL6bgP34=,tag:rAoMbm7D+4qMhyrfraBqsQ==,type:str]
    JELLYFIN_USERNAME: ENC[AES256_GCM,data:eeLbaD4=,iv:IqOGGAlJdQJ4Iba1XekGvu74gO5rQxp5IoHclT3iXvw=,tag:31dLbnAxdsoo9506+9JmZA==,type:str]
    LIDARR_API_KEY: ENC[AES256_GCM,data:bH4Db4gasYAL4lr9hl26yNrIlf7oYs/CYQj75DZmYR0=,iv:zJbX6BbQKqr0U2ikfz0oamwh2OVxP/zigxpJel1tq9E=,tag:p8yZW99m4oy+XRZXUkwAww==,type:str]
    PROWLARR_API_KEY: ENC[AES256_GCM,data:iXbrcpnP3GV1p0rAo+2te4XnOnuBIOZOaxadQaUBrxQ=,iv:HK+WBcJoumUpS/BSZifMIBEQB1LPN7qW0sYQPCksDH8=,tag:U9+j30npRf6GrHX6XeK3yg==,type:str]
    RADARR_API_KEY: ENC[AES256_GCM,data:X5plAmMqzzK6rQ2wzbVIJuQUepIyhUNSqtr/f/ALOq4=,iv:GT2hV9IieDbICFG4cCy2RVZw/8QnfZBc2t/2jFzc+pM=,tag:JLivJCTXejAwUkOxwlHgJw==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:EoE/9Zzd0qh24exw6pLKyAQVsPmCEp1hoq0tsU9z8/o=,iv:oakBtcFnBcdCdAfq+rMiFTNRmAg3OOnoMIfpP4rewoE=,tag:t7/u5tzHymPlNkPZLl1eUw==,type:str]
    WHISPARR_API_KEY: ENC[AES256_GCM,data:WiDKuLrp9GqdwX1n1FGxGgFX1QNM74pGaha1xSL8vv0=,iv:2VOilOcMYHv1Q8XbKyvYwcfdhWQaAW3xOfqNJKe4Abw=,tag:XZBaxDkiYcX5z6oj9mMPyQ==,type:str]
    JELLYSEERR_API_KEY: ENC[AES256_GCM,data:z6tMhRsrVnWobSqs6X/LYB3bCIrNw229+HptvK/iweSRwYLZASquVrujqEW0lsxRjCxvO3u/qty30JqkXUladQ==,iv:w/SPBqbB3DSlAGf55RYuKsPtGaKyresmXBmHoLPwxjU=,tag:Mx98vZoUMA55YrV743XggQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjdDFGVmExK3l3Ylo0d2o2
            WXVOc09OaXNUWFpWeVdBeFFtczdlVFhFUkd3CkFqTmUvOGN1Zy9ZYkU3UW5saEZx
            cFJwNXpoeFc4U3Jpd2t3VGxuQ0lRYlkKLS0tIFFESCtOclVBMDdpa3pWd3ZRYTkw
            MTM4dVl5dGhMRUhlZmlVN2dQUzhVcFEKnzBBtAxlGOH1H947PHqZtBDluMh16pip
            uaFEm0DPT98036DcTsaHG3HPYaxKhgFsQxIc44KfRqhwUsUnICSz4g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vgjxqxjsgk0p46f0fyvnvxrd6sceuhqymyt4h5fsgaanrd2vt3yqpa0054
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-21T05:24:03Z"
    mac: ENC[AES256_GCM,data:GlQcNlS3nN8dvR3lR132JUV+PjZEIluGNcsRKinYw53XMQub0SEjH9DfuQFZjhSz22DMQMW9g9ZRhMFW8xnBTFrwFOTNN9f+tPGeId/A7AsXEb2pjS6axbOQDC/NlP5uqfU63bAsrdNJgF41/nThYE8O+Cfn2F+1Z1TT/zt8QQE=,iv:E6+Ew5jaNeUbI2lZ4jhbRCrqq0FCK9MYIdgTC6oXN1U=,tag:MeuHvfKEERebKLst48vegw==,type:str]
    version: 3.13.2
