apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:+5shX7/14NDQj9Gwj2N9QHZ1TuEQTLHDXxhlOkvjRDa55WXmkDlodr9CPj8Tx0qORZbvpkEcCABNsSgGcsAO9w==,iv:AziiV6RDygIOgo8pSzxcl6urw7Y//mL4gXmUPqjleJw=,tag:56cCkqTAoZS4pVTBJRjNVg==,type:str]
    admin-user: ENC[AES256_GCM,data:q4Tiw8A1YbA=,iv:C4gDzoZvdPBvCj7Ofmxom0AOdYkTmXDhykmSOYRRXe8=,tag:S4w8ttP0tKcn3YnIR9XeGg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: grafana-admin
    namespace: observability
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5T3lMSjIvNnVHTTdNZXl3
            MlozajdSeCtNL2UxVHFWM3dpOG5BZUtIZFNVCkExV21GRXJxdmtTbW41Mm5yWmNX
            QnhXVmpvSWZLSWxQbEJ6T1FtaDRMTHcKLS0tIHpxWkJ1VWNJWVQ1RVdRMVBZWTBm
            eG5sLzF5VVBDNVF0ZGF1MEVwbzlEak0KC/HkN1ax8bI1WBKog/95V0Mgc2PIbNfN
            xaNY1zoZPiTYdWnQS3ROiC1ZBLVOGGw4kcdMWkwHrbaTdV0VLCOIZg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vgjxqxjsgk0p46f0fyvnvxrd6sceuhqymyt4h5fsgaanrd2vt3yqpa0054
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T05:21:50Z"
    mac: ENC[AES256_GCM,data:ShMHdF9zjQJxTvovyWaRqci6xNW74MgI//6dtsB9/7FPlEgec+Yu7jmWOT3mPd44sJP9C0RbbJ7sMEkt3E+2eHCt0IESV/vl70OhetTJ+ny2IIno2KyjU3R4Bc6CFyZCNybIJCdzCHLM+29J/tllFup7nzrGIW5Qv9GX0d2FhOw=,iv:y0tUb/FYIiGyCvWZj6isfeTAIMoaY5Hk3p9/tJTtMSc=,tag:87prOyxrxBnIdAOtZNOgZw==,type:str]
    version: 3.13.2
