apiVersion: v1
kind: Secret
metadata:
    creationTimestamp: null
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:qYHAcJZsK2Dz/9ZmReSJSHUsEUfF54+aUwch7T4e4kWOyrwsufLgRWeShFGM1ybJ/CF1ykf3E1fSD6ki,iv:OC6lP5SKGgHLopQ/dbGHPYlLe8REaRfB6AeFKkE1wWs=,tag:ImNAL7WLP/hLp3eqcOgtOQ==,type:str]
    username: ENC[AES256_GCM,data:6Th39sTHv/T6Lg==,iv:BnEzvzBB3pnR/v7nS/HzJSxF0F1aiQ1CjqQJ90a78ns=,tag:/1qFGbFCOfexLHyYA49Ztw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZ0hiMkJPaUFQb2tENktP
            ZEpYYnhRRGtJOTJBUEsvM3d1UHNWc3ZsU2h3CmdqSkp6Y095eG9yb043a2xSVTZ1
            SU9YaUhJanBNK1JIbnZUUHhOUEJ2MFkKLS0tIE4rYUtUbVQxaC8zdW9UUHEvRzEr
            NC9zYUt4bEF5ZkxqTzdQK0ZvOTh5NzAKzrqHPcfCFvDpat7HDLLLOyiNIMs939Ob
            jyYB7zS4V8YC2hJuvUwQY8WHdF/hcKfKX4B0hunPEq0Y5MYqiRE3Zw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vgjxqxjsgk0p46f0fyvnvxrd6sceuhqymyt4h5fsgaanrd2vt3yqpa0054
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-21T03:59:50Z"
    mac: ENC[AES256_GCM,data:vkvVy4I10oHDEv/LV2fyov+1uptPIaffwlzRJcaCU6CUNOs9xfOZX+eMooynN+PhQs/iECYk8pNF3GIqTJKfdBAyJjrgARTl60pO0Df2rDU7yscuJ7PackM5ayUr9kYkeUh4mnvn2yFrXp8QXpsumLe/f5zM9bw7vIoM+zYnlec=,iv:OsVUkrANrVoP6ITTkU4Ib8mascWBM2ekB+ocK3a/z+s=,tag:Cqbzkv5uuPVkbbRE5WoKxw==,type:str]
    version: 3.13.2
