apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  chartRef:
    kind: OCIRepository
    name: weave-gitops-chart
  driftDetection:
    mode: enabled
  install:
    remediation:
      retries: 3
  interval: 2m
  timeout: 10m
  upgrade:
    cleanupOnFail: true
    remediation:
      remediateLastFailure: true
      retries: 3
      strategy: rollback
  valuesFrom:
    - kind: ConfigMap
      name: weave-gitops-values
      valuesKey: values.yaml
