fullnameOverride: weave-gitops

image:
  repository: ghcr.io/weaveworks/wego-app
  tag: v0.38.0@sha256:dd2ff7daf1711b190b1b12ac965c6a43c11c13b229af3aa5ebf9035382bbcc59
  pullPolicy: IfNotPresent

adminUser:
  create: true
  createClusterRole: true
  createSecret: false
  username: wego-admin

rbac:
  create: true
  impersonationResourceNames:
    - wego-admin
  impersonationResources:
    - users
  viewSecretsEnabled: true
  viewSecretsResourceNames:
    - cluster-user-auth

networkPolicy:
  create: true

nodeSelector:
  homelab.bupd.xyz/workload-pool: media

resources:
  limits:
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

service:
  create: true
  type: ClusterIP
  port: 9001

ingress:
  enabled: false
