---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dagger
  namespace: dagger
spec:
  chart:
    spec:
      chart: dagger-helm
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: dagger
      version: 0.18.2
  interval: 1m0s
