apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - storage.yaml
  - source.yaml
  - release.yaml
  - ingress.yaml

configMapGenerator:
  - name: jellyfin-values
    namespace: media
    files:
      - values.yaml
    options:
      labels:
        reconcile.fluxcd.io/watch: Enabled

generatorOptions:
  disableNameSuffixHash: true
