apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  chartRef:
    kind: OCIRepository
    name: jellyfin-chart
  driftDetection:
    mode: enabled
  install:
    remediation:
      retries: 3
  interval: 2m
  timeout: 15m
  upgrade:
    cleanupOnFail: true
    remediation:
      remediateLastFailure: true
      retries: 3
      strategy: rollback
  valuesFrom:
    - kind: ConfigMap
      name: jellyfin-values
      valuesKey: values.yaml
