apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Ti
  hostPath:
    path: /home/bupd/hdd/data
    type: Directory
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - media-worker
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-data
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
  storageClassName: ""
  volumeName: media-data
