apiVersion: v1
data:
    .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovLzhnZWFycy5jb250YWluZXItcmVnaXN0cnkuY29tIjp7InVzZXJuYW1lIjoicm9ib3RfOGdjcitidXBkX3B1bGwiLCJwYXNzd29yZCI6IlRDTGYzSlZMYzBKSmxHSU53cGRMQlV4V3V5M3VMNkVUIiwiYXV0aCI6ImNtOWliM1JmT0dkamNpdGlkWEJrWDNCMWJHdzZWRU5NWmpOS1ZreGpNRXBLYkVkSlRuZHdaRXhDVlhoWGRYa3pkVXcyUlZRPSJ9fX0=
kind: Secret
metadata:
    creationTimestamp: "2025-03-26T03:28:12Z"
    name: 8gears-cr-cred
    namespace: container-registry
    resourceVersion: "2514603402"
    uid: 5b7248a8-0c60-420d-9aaa-21f887167530
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age1vgjxqxjsgk0p46f0fyvnvxrd6sceuhqymyt4h5fsgaanrd2vt3yqpa0054
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5QVV1c0NhWXZuUEtZSmR4
            VGIvbitFMFB5ZnVXb095b2NJMmQreG5lcm5RCmVIWXZOMzVjWCtYY0pOTHZ1MTVF
            V2dOSjF3RzJpcytxRWpDQnhrWEJpQVkKLS0tIG82RWVDbHJDcFBwdDBFK2gyTjhE
            ZDg4amxtamgxbkdrSENleC9yWnBXaEUKJZ6oEvmliwzEo0qxuxa6G65iMLiKeys6
            UU5MI3JO7M8JU/eyESumVyLzvKBG2txtvpzWhgk/Fb9chxwJXQTxxQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l94nxjefdnlew2lzdpr2dc52vm8qt024ql5nuyefar9g32ph7cxq8u6r7s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxOWpCQnhrTDQzSHdjYXhV
            czlERWVWVkVpRm5UcW1DL2xjZ2ozbzE5NDNjClFnQzg4M1Q1VHQxRVgrR2d6NktY
            TWFjZ1crRTR6TUpxU085N2EzTUVNTE0KLS0tIDB6KzFRTlUvbW9lRU5PMitZVzQy
            ZnNPNGNmUkNXYWYyeVE3ODdCcVFEY0UKcikncM/5Qj01GoWrdYikp4jDVJhLNbOU
            uuIGh0lok+Hpe9Hv1l7PcgB/VAoViiTB2b6GZJRKZTnW+FBtxILJJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-09T01:39:09Z"
    mac: ENC[AES256_GCM,data:XXsrXENDYUwdmZp8EYwm2N2ZW7vHOgzJv3hiVaBMYlsww0jTbV7dz/QK/EdrJws4hSAs36xIg5tLaWijGBphNrBWAM4MKuzu6gwRYyt1zFUbbx4WNhNziVd4q22aKlwega5jRsbI9wTWo+JoI6VhR0PPyGmRv0gfsL0aNQw6czM=,iv:6R/qOUXU+Xo7TpBi6UBIrc64xK6wFZcP7PXhYy0MFPQ=,tag:dHgdv/5ExjMrY6KVSWNfHg==,type:str]
    encrypted_regex: (password|secret|key|token|user)
    version: 3.10.2
