apiVersion: v1
kind: Node
metadata:
  name: media-worker
  labels:
    homelab.bupd.xyz/node-class: worker
    homelab.bupd.xyz/workload-pool: media
    homelab.bupd.xyz/storage: media
    homelab.bupd.xyz/accelerator: nvidia
