apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-operator
  namespace: flux-system
spec:
  chartRef:
    kind: OCIRepository
    name: flux-operator-chart
  driftDetection:
    mode: enabled
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  interval: 2m
  timeout: 10m
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
      retries: 3
      strategy: rollback
  valuesFrom:
    - kind: ConfigMap
      name: flux-operator-values
      valuesKey: values.yaml
