apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
type: Opaque
data:
    admin-username: ENC[AES256_GCM,data:G//QjZWcgg==,iv:lMptsnpzGjxqhof5cJb4wu2aEigoELl7iw17N74ICrw=,tag:FElZtO4tmzTu2BitcuGAHA==,type:str]
    admin-password: ENC[AES256_GCM,data:zCtf6TE71TEYQS0N,iv:pE0uWMmIZcGKpJMiL9+5FFndNI7EUsloKuSK1CJaB3o=,tag:EBSZhst7mopT7Xh7caoFcQ==,type:str]
sops:
    age:
        - recipient: age1vgjxqxjsgk0p46f0fyvnvxrd6sceuhqymyt4h5fsgaanrd2vt3yqpa0054
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnUHhSOWZPdnVKeGVNTkZO
            VlJneFY4REVmVW0zcFY0allxRGFvTVEwSENZClhaeDBrenA3VlNpNExFSmxEaGR2
            eHNFWmxLcE91alE5aXZUSE1KQ2Q5ajAKLS0tIHI2cE9PY3FxMDd2bmo3aFdhcGlL
            a1ZwR2xmaVdQV0ttQ0ZBeXNTMEdOb0kKe8OZQJVG+2gXNe1K3GlzHyVz9CFEqgXq
            k7NjIrVuEA3T1TP1k33QhdMl8DdK+M/XJW+jvRYn1BR6d3XVUw08Vw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l94nxjefdnlew2lzdpr2dc52vm8qt024ql5nuyefar9g32ph7cxq8u6r7s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBT0VxcndZSWlnSElBNkd0
            dWt5QzZ0M08rejFjUlVJTmI0YzEra3pNYUJvCldXekd2S0oxcml0RUkrVk1XWitw
            d2NCMEwwR01IVUwyZHFFa3ZqdlpnZncKLS0tIEpkM2NJZzVMdG9iT3czaDBubEV6
            WWtWbzBkb1Vzd1BRMnBMRHVKTU5ndzgKv1+D8TRQNEb6STY32hTtgmqZ2CkCPpcX
            SKTeun4VrQvHpgYP+fE0RdMzsiOZsuO9CBgZDS+dsaBcJkPsvN+PKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-03T21:21:40Z"
    mac: ENC[AES256_GCM,data:4F5lzxL/lzKegzGKbj4/qAmlwco9kPBBOU+f000REI8G7GBbQovugdeM6OOQ+yMqn+O5AuPRhl4bRmT+c5ek09SmfeKfUfv1Y9+iZjhST8QHGgbys92/Xzm+LILhcdfIPtliWMIiZEY3kXatw+9wmCiehOnAL7/q5nU1uLV/DjY=,iv:n5RNHEsbguW5mEGGy/fhyA/lKg5ZkrKz8Rzjg7HgjDo=,tag:m9f0jQg2X9LUOzb8YTAB8Q==,type:str]
    encrypted_regex: (password|secret|key|token|user)
    version: 3.10.2
