apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
type: Opaque
data:
    admin-user: ENC[AES256_GCM,data:TuUHZBB8Ids=,iv:a/fusY9oNmeBAHoDs/MjtG1CiFlqBuX80nZ080OCR1k=,tag:JmGGXh2vAbmGP0ozYPmDPw==,type:str]
    admin-password: ENC[AES256_GCM,data:+yKBlrCYFR3ZUTmX,iv:r4NwCBqO3iZ7ykBubMeU7gKMOH8JgSXExROvD9QW0tE=,tag:zmuHuaIjbZKoQIJOUh1Oxw==,type:str]
sops:
    age:
        - recipient: age1vgjxqxjsgk0p46f0fyvnvxrd6sceuhqymyt4h5fsgaanrd2vt3yqpa0054
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGaFN6T2pBTVZmWjZPWjZ5
            cS85ZjJlbFdYdFBDNE9QNVpLWk1XTkpHNDI4CkdxUW5VSG8xMXBCSTRZUjFMa0NC
            aXdkOUlVeFdqWk9xR2YyWmM0djVLZUUKLS0tIEJHQVY3YjJBa2d5QTVRT281UURz
            c1U5SzBVV0pLZWZGbm1VNHZmdVowM0EK8T9QM+w4PXOmItOW/KnjJGpWHzyES0cd
            uWxCoa2hnIOm2BpfholVCLuvitWj1/HjbjAwRPQpabaN7mkfQ0+y2Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l94nxjefdnlew2lzdpr2dc52vm8qt024ql5nuyefar9g32ph7cxq8u6r7s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBScjcyTGl0TkRUL0FVUTRG
            Tld6TXRwbXF5TjlCSThpK3dyKzhMWjhJNmpnCjRwbDJPWUpVZTVRR1Mwb0psMHRq
            b3EvcnliZUxBTG5JS3BXd1A2SXNYZEEKLS0tIDNjUkhRT1FtMFRXVkc0c1gxK2lS
            WjY3cXNlYW1KTFI2d0dpcjJ0ajZ5Wm8KX4s0m9/78WRxMx4bMshjvCiuZfSj/puq
            wu47z5SR+GU5zqh5h8Y344F4wr7SktDYhJOYJ1FHOJtOGAt9KXoN0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-03T21:45:38Z"
    mac: ENC[AES256_GCM,data:i5PU06zWGGlhSyahampLPd6475++8aDP0mVWAG5Dibz7A/CvLkS+US28nR8aZ1m3jTFiX/EaVuFTSzRLe7XXz6+7CMnU3jHI/4hbYlwUGHo4zQrSUbcZGpwRQ4w0wfLfY+NbEkZWiFdUQItgKE5fBkLYODrHSp356oZn8oXj/Aw=,iv:nlwoK1UhyG9T22uT0V+Iy3DT8c6jWUTrcpPzBzEDr5A=,tag:maQRe80g/7A+skQLRtnMow==,type:str]
    encrypted_regex: (password|secret|key|token|user)
    version: 3.10.2
