apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
type: Opaque
data:
    admin-user: ENC[AES256_GCM,data:fIK0KjY8VWI=,iv:uW6SkFl35U7SxcIuw5gbdmvBL5NYiCzYa2gLG/mC0Xs=,tag:hYQyvxXBi/4AdXZmz//cbw==,type:str]
    admin-password: ENC[AES256_GCM,data:uRq701snOMucAoMT,iv:JarVacCrC+OMJ1tTRX2nlAcvw8fSCkFCY/9ZrjL7bPY=,tag:iFRw5SgtK2YdYxM1N1bgBA==,type:str]
sops:
    age:
        - recipient: age1vgjxqxjsgk0p46f0fyvnvxrd6sceuhqymyt4h5fsgaanrd2vt3yqpa0054
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzWUkxbE5xTFRhZEprU2tT
            c2FVdFBuTmZqZytVNTNQVDJ2ZVhxYzhubDBNCmwzbmR6a083eGhNL1hFaDVGU1Nx
            TWFMRGhvYXNZeng4T21oTEx1RW5TeXMKLS0tIElBSnVlaVN0NnRMd3N0WmpRV295
            WWtSR2hDMmV3elNiVVhlcXBEZVFrUjQKxroG75ucU7tluXv16S9dYWqCwIyKlxTF
            TZ8Nle6B2leWv8vK09DezG++q/iwfz1NxYWgnrnxmxXposUW4tBZTQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l94nxjefdnlew2lzdpr2dc52vm8qt024ql5nuyefar9g32ph7cxq8u6r7s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3bzQzUUEyalJMbUVrRGsx
            SC8xU0hqY3VZMGd3MkJMRnBsMHNDNHIwTWtFCmlTd3Z5cFdpNGI2UnJWbFh5Wnh2
            aE1DWVZXY2lVc0d5UHBWM1lxc1NUaTAKLS0tIG8wZWdiSDV0YkhrU05FMmlQeU5B
            WjN4S0t3Mm1xQWZPRWhtUXAyMW50ZU0K0hPKHb6x6Z0pl5EhSS3RnHipius15uTR
            Dy6as51siKUW082vFspb850ZIM3LWRjKPp88JXjOT9fyvZhE4XxCIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-03T22:33:41Z"
    mac: ENC[AES256_GCM,data:ZXNd+qbhwsjFn5tqMVUI1qcfUwfrilTgCpBF+ZLKA1VQPfzeSFIPQNNYCl31E5PShgWcurSpeW+o9dKTGEssOrRKYMd6wGotBHe9MVzVm7jVqoOiX+9sgSAdFsWBoaE9cqvF2BqJs0sDwNsYTudF4ThRXzzp8TflMz5+RDjRnN0=,iv:d2munZbUmiYVTIEJGUdgY0beB2b95SdTIKLGpy9+i2k=,tag:NAXI/yYyoHONcIxX44EtzA==,type:str]
    encrypted_regex: (password|secret|key|token|user)
    version: 3.10.2
