# config to be supplied to flux instance to work with git repo
apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
spec:
  distribution:
    version: "2.x"
    registry: "ghcr.io/fluxcd"
  sync:
    kind: GitRepository
    url: "https://github.com/bupd/homelab.git"
    ref: "refs/heads/main"
    path: "flux/my-cluster"
    # omitted since the repo is public
    pullSecret: "flux-git-auth"
    decryption:
      provider: sops
      secretRef:
        name: sops-age

