apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - external-library-storage.yaml
  - library-storage.yaml
  - mobile-booky-storage.yaml
  - prasanth-storage.yaml
  - source.yaml
  - release.yaml
  - ingress.yaml

configMapGenerator:
  - name: immich-values
    namespace: immich
    files:
      - values.yaml
    options:
      labels:
        reconcile.fluxcd.io/watch: Enabled

generatorOptions:
  disableNameSuffixHash: true
