apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-managed-library
  namespace: immich
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/component: library
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-path
  volumeMode: Filesystem
